#line 1 "/home/jbhall/software_build/codegen_6502/test/lexer.cpp"

#line 3 "/home/jbhall/software_build/codegen_6502/test/lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 105
#define YY_END_OF_BUFFER 106
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[236] =
    {   0,
        0,    0,  106,  104,    1,    1,  104,  100,  104,  104,
      102,  103,   96,  101,   97,  104,   94,    2,   98,   95,
       99,   91,   27,   28,  104,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
        1,    0,    6,   92,   93,    0,    7,    7,    7,   94,
        2,   91,   26,   91,    0,    0,    0,    0,    0,   26,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,

       26,    0,    7,    3,    5,    0,    0,    0,    0,    0,
        0,   15,    0,   53,   48,   65,   72,   73,   74,   51,
       75,   76,   77,   87,   78,   79,   80,   81,   82,   83,
       55,   56,   57,   52,   61,   63,   64,   49,   58,   59,
       60,   69,   70,   33,   29,   30,   31,   66,   88,   50,
       44,   45,   46,   47,   39,   67,   68,   89,   71,   90,
       54,   84,   85,   86,   62,   32,   34,   35,   36,   37,
       38,   42,   40,   43,   41,    0,    0,    0,    7,    0,
        0,    0,    0,    0,   10,   15,    0,    0,   11,    0,
        0,    4,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   20,    0,    0,    0,    0,
        0,   23,   25,    0,    0,    0,    0,    0,   13,   24,
       14,   22,    0,   19,   12,    0,    0,   21,   18,    8,
        9,    0,   16,   17,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    6,    7,    1,    1,    8,
        9,    1,   10,   11,   12,   13,    1,   14,   14,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,   20,    1,    1,   21,   21,   21,   21,   21,   21,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   23,   24,   22,
        1,    1,    1,    1,   25,    1,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,    1,   52,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[53] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        1,    1,    1,    4,    4,    5,    1,    1,    1,    1,
        6,    7,    7,    7,    7,    8,    8,    8,    8,    8,
        8,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    1
    } ;

static const flex_int16_t yy_base[255] =
    {   0,
        0,    0,  452,  720,   51,   53,  441,  720,    0,   43,
      413,  720,  720,  720,  720,   31,   47,    0,  720,  720,
      720,   49,   52,   55,   44,   68,   97,   80,   48,   61,
       67,  105,  121,   92,   73,  115,  117,  140,  138,  152,
       85,  427,  720,    0,   76,  377,    0,  367,   67,  108,
        0,  394,  720,  154,  377,  350,  340,  359,  357,  114,
      166,  168,  161,  173,  178,  184,  189,  194,  196,  202,
      208,  213,  218,  218,  220,  237,  232,  246,  239,  241,
      251,  257,  256,  267,  272,  277,  285,  290,  292,  300,
      283,  308,  314,  313,  322,  321,  329,  331,  338,  340,

      155,  351,  331,    0,    0,  329,  328,  324,  331,  313,
        0,    0,  116,  331,  354,  356,  361,  363,  368,  370,
      375,  377,  382,  384,  389,  391,  396,  398,  403,  405,
      410,  412,  417,  419,  424,  426,  431,  433,  438,  440,
      445,  447,  452,  454,  459,  461,  466,  468,  473,  475,
      480,  482,  487,  489,  494,  496,  501,  503,  508,  510,
      515,  517,  522,  524,  529,  531,  536,  538,  543,  545,
      550,  552,  557,  559,  564,    0,  293,  296,  295,  293,
      289,  271,  272,  266,    0,    0,  259,  245,    0,  240,
      239,    0,  228,  223,  203,  181,    0,  168,  169,  165,

        0,    0,    0,    0,  175,    0,  170,  161,  159,  158,
      143,  135,  118,    0,   78,    0,    0,  148,  720,  720,
      720,   84,    0,    0,    0,   83,   63,  720,   48,  720,
      720,  150,  720,  720,  720,  605,  611,  612,  621,  627,
      633,  640,  646,  651,  657,  662,  668,  674,  680,  686,
      692,  698,  704,  710
    } ;

static const flex_int16_t yy_def[255] =
    {   0,
      235,    1,  235,  235,  235,  235,  236,  235,  237,  235,
      235,  235,  235,  235,  235,  238,  235,  239,  235,  235,
      235,  240,  240,  240,  235,  240,   26,   26,   28,   28,
       28,   28,   26,   28,   28,   28,   28,   28,   28,   28,
      235,  236,  235,  237,  235,  235,  238,  238,  238,  235,
      239,  241,  235,   28,  235,  235,  235,  235,  235,  242,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   39,   28,   39,   28,   39,   28,   28,
       28,   39,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   72,   28,   28,   39,   39,   39,   39,   39,

      235,  235,  238,  238,  238,  235,  235,  235,  235,  235,
      243,  244,  235,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,  245,  235,  235,  238,  235,
      235,  235,  235,  235,  243,  244,  235,  235,  245,  235,
      235,  238,  235,  235,  235,  235,  246,  235,  235,  235,

      247,  248,  249,  250,  235,  246,  235,  235,  235,  247,
      248,  249,  250,  251,  235,  252,  253,  235,  235,  235,
      235,  251,  254,  252,  253,  235,  235,  235,  254,  235,
      235,  235,  235,  235,    0,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235
    } ;

static const flex_int16_t yy_nxt[773] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   17,    4,   18,   19,   20,   21,
       22,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       22,   22,   22,   31,   32,   22,   33,   22,   34,   35,
       36,   22,   37,   38,   39,   22,   22,   22,   23,   24,
       40,    4,   41,   41,   41,   41,   45,   48,  232,   49,
       50,   50,   52,   52,   53,   52,   52,   53,   52,   52,
       53,  231,   55,   52,   56,   75,   52,   76,   57,   52,
       58,   52,   52,   60,   54,   54,   41,   41,   54,   45,
       59,  230,   52,  104,   45,   53,   61,   54,   54,  228,

       77,   54,  223,   54,   54,   78,   62,   54,   54,   54,
       54,   63,   53,   54,  105,   85,   72,   73,   54,  111,
       74,   50,   50,   54,   64,   54,   65,   45,   54,   54,
       66,   84,   54,  221,   67,   68,   53,   69,  113,   70,
       54,   54,   79,   71,  187,   54,   81,   86,   80,   82,
      220,   87,   54,   88,   54,   54,   89,   54,  219,   54,
      176,   90,  188,   97,   83,   91,   92,  101,  218,   93,
      226,  227,  233,  234,   54,   54,   94,   54,   54,  177,
       54,   98,   95,  217,   96,  216,   99,  100,   54,   54,
       54,   54,   54,  114,   54,  215,  115,  116,   54,  214,

      117,   54,   54,   54,   54,   54,   54,  209,   54,   54,
       54,  208,  207,   54,   54,   54,  118,  205,   54,  119,
       54,   54,  121,  122,   54,   54,   54,  204,  120,   54,
       54,   54,  123,   54,   54,  125,   54,  124,   54,   54,
      127,  128,   54,   54,   54,   54,  129,  203,   54,   54,
       54,  126,  202,   54,   54,   54,   54,   54,  131,  130,
      134,   54,   54,  201,  135,  200,  132,  133,   54,   54,
      199,   54,   54,  139,  138,   54,   54,   54,   54,  142,
       54,   54,  145,  143,  198,  136,  137,   54,   54,   54,
      197,   54,   54,   54,  140,  141,   54,  150,  148,  144,

       54,  196,  151,   54,   54,  146,  147,  149,   54,   54,
      153,  195,   54,   54,   54,  155,  194,  152,  193,   54,
       54,   54,   54,   54,  192,  154,   54,   54,  156,   54,
       54,  160,   54,  158,  157,  161,   54,   54,  191,  190,
       54,  162,  163,  159,   54,   54,  167,  164,   54,   54,
       54,  166,  165,   54,   54,  184,   54,  183,   54,   54,
       54,  182,   54,  173,   54,  175,  181,   54,   54,  168,
      169,   54,   54,  180,   54,  179,  178,  170,  171,  172,
       54,  174,  110,   54,  109,  108,   54,   54,   54,   54,
       54,   54,   54,   54,   54,  107,   54,   54,   54,   54,

       54,   54,  106,   54,   54,   54,   54,   54,   54,   53,
       54,   54,   54,   54,   54,   54,  103,   54,   54,   54,
       54,   54,   54,  102,   54,   54,   54,   54,   54,   54,
       43,   54,   54,   54,   54,   54,   54,   46,   54,   54,
       54,   54,   54,   54,   43,   54,   54,   54,   54,   54,
       54,  235,   54,   54,   54,   54,   54,   54,  235,   54,
       54,   54,   54,   54,   54,  235,   54,   54,   54,   54,
       54,   54,  235,   54,   54,   54,   54,   54,   54,  235,
       54,   54,   54,   54,   54,   54,  235,   54,   54,   54,
       54,   54,   54,  235,   54,   54,   54,   54,   54,   54,

      235,   54,   54,   54,   54,   54,   54,  235,   54,   54,
       54,   54,   54,   54,  235,   54,   54,   54,   54,   54,
       54,  235,   54,   54,   54,   54,   54,   54,  235,   54,
       54,   54,   54,   54,   54,  235,   54,   54,   54,   54,
       54,   54,  235,   54,   54,   54,   54,   54,   54,  235,
       54,   54,   54,   54,   54,   54,  235,   54,   54,   54,
       54,   54,   54,  235,   54,   54,   54,   54,   54,   54,
      235,   54,   54,   54,   54,   54,   54,  235,   54,   54,
       54,   54,   54,   54,  235,   54,   54,   54,   54,   54,
       54,  235,   54,   54,   54,   54,   54,   54,  235,   54,

       54,   54,  235,  235,   54,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   44,  235,   44,  235,   44,   47,
       47,   51,  235,   51,   51,   51,   51,   51,   51,   51,
       54,   54,   54,   54,   54,   54,   52,   52,   52,   52,
       52,   52,  112,  235,  235,  112,  112,  112,  112,  185,
      235,  185,  235,  185,  186,  235,  186,  186,  186,  186,
      189,  235,  189,  235,  189,  206,  235,  206,  206,  206,
      206,  210,  235,  210,  210,  210,  210,  211,  235,  211,
      211,  211,  211,  212,  235,  212,  212,  212,  212,  213,
      235,  213,  213,  213,  213,  222,  235,  222,  222,  222,

      222,  224,  235,  224,  224,  224,  224,  225,  235,  225,
      225,  225,  225,  229,  235,  229,  229,  229,  229,    3,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235
    } ;

static const flex_int16_t yy_chk[773] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    5,    6,    6,   10,   16,  229,   16,
       17,   17,   22,   22,   22,   23,   23,   23,   24,   24,
       24,  227,   25,   22,   25,   29,   23,   29,   25,   24,
       25,   26,   26,   26,   29,   29,   41,   41,   29,   45,
       25,  226,   26,   49,   10,   28,   26,   30,   30,  222,

       30,   30,  215,   31,   31,   31,   26,   31,   28,   35,
       35,   26,   27,   35,   49,   35,   28,   28,   28,   60,
       28,   50,   50,   28,   27,   27,   27,   45,   34,   34,
       27,   34,   34,  213,   27,   27,   33,   27,   60,   27,
       27,   32,   32,   27,  113,   32,   33,   36,   32,   33,
      212,   36,   36,   37,   37,   36,   37,   37,  211,   33,
      101,   37,  113,   39,   33,   38,   38,   40,  210,   38,
      218,  218,  232,  232,   39,   39,   38,   38,   39,  101,
       38,   39,   38,  209,   38,  208,   39,   39,   40,   40,
       54,   54,   40,   61,   54,  207,   62,   63,   63,  205,

       64,   63,   61,   61,   62,   62,   61,  200,   62,   64,
       64,  199,  198,   64,   65,   65,   64,  196,   65,   65,
       66,   66,   67,   68,   66,   67,   67,  195,   66,   67,
       68,   68,   69,   69,   68,   71,   69,   70,   70,   70,
       72,   72,   70,   74,   71,   71,   72,  194,   71,   72,
       72,   71,  193,   72,   73,   73,   75,   75,   73,   72,
       75,   74,   76,  191,   76,  190,   74,   74,   77,   77,
      188,   78,   77,   78,   77,   79,   79,   80,   80,   79,
       76,   80,   82,   80,  187,   76,   76,   81,   81,   78,
      184,   81,   83,   83,   78,   78,   83,   85,   83,   81,

       82,  183,   86,   84,   84,   82,   82,   84,   85,   85,
       87,  182,   85,   86,   86,   88,  181,   86,  180,   91,
       91,   87,   87,   91,  179,   87,   88,   88,   89,   89,
       88,   91,   89,   90,   89,   92,   90,   90,  178,  177,
       90,   93,   93,   90,   92,   92,   96,   93,   92,   94,
       94,   95,   94,   94,   97,  110,   98,  109,   95,   95,
       93,  108,   95,   99,   96,  100,  107,  114,  114,   96,
       96,  114,   97,  106,   98,  103,  102,   97,   97,   98,
       98,   99,   59,  100,   58,   57,   99,   99,  100,  100,
      115,  115,  116,  116,  115,   56,  116,  117,  117,  118,

      118,  117,   55,  118,  119,  119,  120,  120,  119,   52,
      120,  121,  121,  122,  122,  121,   48,  122,  123,  123,
      124,  124,  123,   46,  124,  125,  125,  126,  126,  125,
       42,  126,  127,  127,  128,  128,  127,   11,  128,  129,
      129,  130,  130,  129,    7,  130,  131,  131,  132,  132,
      131,    3,  132,  133,  133,  134,  134,  133,    0,  134,
      135,  135,  136,  136,  135,    0,  136,  137,  137,  138,
      138,  137,    0,  138,  139,  139,  140,  140,  139,    0,
      140,  141,  141,  142,  142,  141,    0,  142,  143,  143,
      144,  144,  143,    0,  144,  145,  145,  146,  146,  145,

        0,  146,  147,  147,  148,  148,  147,    0,  148,  149,
      149,  150,  150,  149,    0,  150,  151,  151,  152,  152,
      151,    0,  152,  153,  153,  154,  154,  153,    0,  154,
      155,  155,  156,  156,  155,    0,  156,  157,  157,  158,
      158,  157,    0,  158,  159,  159,  160,  160,  159,    0,
      160,  161,  161,  162,  162,  161,    0,  162,  163,  163,
      164,  164,  163,    0,  164,  165,  165,  166,  166,  165,
        0,  166,  167,  167,  168,  168,  167,    0,  168,  169,
      169,  170,  170,  169,    0,  170,  171,  171,  172,  172,
      171,    0,  172,  173,  173,  174,  174,  173,    0,  174,

      175,  175,    0,    0,  175,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  237,    0,  237,    0,  237,  238,
      238,  239,    0,  239,  239,  239,  239,  239,  239,  239,
      240,  240,  240,  240,  240,  240,  241,  241,  241,  241,
      241,  241,  242,    0,    0,  242,  242,  242,  242,  243,
        0,  243,    0,  243,  244,    0,  244,  244,  244,  244,
      245,    0,  245,    0,  245,  246,    0,  246,  246,  246,
      246,  247,    0,  247,  247,  247,  247,  248,    0,  248,
      248,  248,  248,  249,    0,  249,  249,  249,  249,  250,
        0,  250,  250,  250,  250,  251,    0,  251,  251,  251,

      251,  252,    0,  252,  252,  252,  252,  253,    0,  253,
      253,  253,  253,  254,    0,  254,  254,  254,  254,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[106] =
    {   0,
1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "asm6502.l"
#line 5 "asm6502.l"
#include <string.h>
#include "ast.hpp"
#include "util.hpp"
#include "parser.hpp"

#define YY_USER_ACTION yylloc.first_line = yylloc.last_line = yylineno;

void yyerror(const char *);
#line 734 "/home/jbhall/software_build/codegen_6502/test/lexer.cpp"
#line 735 "/home/jbhall/software_build/codegen_6502/test/lexer.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 15 "asm6502.l"

#line 954 "/home/jbhall/software_build/codegen_6502/test/lexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 236 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 720 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 16 "asm6502.l"
{
    ;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 20 "asm6502.l"
{
    mapComment(yylineno, yytext);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 24 "asm6502.l"
{
    return DATABYTES;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 28 "asm6502.l"
{
    return DATABYTES; // Map .byte to the same token as .db
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 32 "asm6502.l"
{
    return DATAWORDS;
}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 36 "asm6502.l"
{
    yylval.str = DUP_YYTEXT;
    return STRING;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 41 "asm6502.l"
{
    yylval.str = DUP_YYTEXT;
    return DIRECTIVE;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 46 "asm6502.l"
{
    // Extract variable name without parentheses and register
    char* originalText = strdup(yytext + 1); // Skip the opening parenthesis
    char* commaPos = strchr(originalText, ',');
    *commaPos = '\0';  // Terminate at the comma
    
    // Skip past "_var_"
    char* varName = originalText + 5;
    
    char* result = strdup(varName);
    free(originalText);
    
    // Create a node with the indirect-indexed addressing mode
    yylval.str = result;
    return NAME;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 63 "asm6502.l"
{
    // Extract variable name without parentheses and register
    char* originalText = strdup(yytext + 1); // Skip the opening parenthesis
    char* commaPos = strchr(originalText, ',');
    *commaPos = '\0';  // Terminate at the comma
    
    // Skip past "_var_"
    char* varName = originalText + 5;
    
    char* result = strdup(varName);
    free(originalText);
    
    // Create a node with the indirect-indexed addressing mode
    yylval.str = result;
    return NAME;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 80 "asm6502.l"
{
    // Strip the "a:" prefix and keep the hex constant
    char* hexRef = strdup(yytext + 2); // Skip past "a:"
    yylval.str = hexRef;
    return HEXCONST;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 87 "asm6502.l"
{
    // Strip the "z:" prefix and keep the hex constant
    char* hexRef = strdup(yytext + 2); // Skip past "z:"
    yylval.str = hexRef;
    return HEXCONST;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 94 "asm6502.l"
{
    // Strip the z:_var_ prefix
    char* varRef = strdup(yytext + 7); // Skip past "z:_var_"
    yylval.str = varRef;
    return NAME;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 101 "asm6502.l"
{
    // Strip the _data_ prefix and the trailing colon
    char* originalText = strdup(yytext);
    int len = strlen(originalText);
    originalText[len-1] = '\0';  // Remove colon
    char* dataName = originalText + 6;  // Skip past "_data_"
    yylval.str = strdup(dataName);
    free(originalText);  // Free the temporary string
    return LABEL;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 112 "asm6502.l"
{
    // Strip the _jump_ prefix and the trailing colon
    char* originalText = strdup(yytext);
    int len = strlen(originalText);
    originalText[len-1] = '\0';  // Remove colon
    char* jumpName = originalText + 6;  // Skip past "_jump_"
    yylval.str = strdup(jumpName);
    free(originalText);  // Free the temporary string
    return LABEL;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 123 "asm6502.l"
{
    // Strip the "a:" prefix and keep the name
    char* nameRef = strdup(yytext + 2); // Skip past "a:"
    yylval.str = nameRef;
    return NAME;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 130 "asm6502.l"
{
    // Extract just the data name (without prefix and indexing)
    char* originalText = strdup(yytext);
    char* commaPos = strchr(originalText, ',');
    *commaPos = '\0';  // Terminate string at the comma
    
    // Skip past "a:_data_"
    char* dataName = originalText + 8;
    
    char* result = strdup(dataName);
    free(originalText);
    
    yylval.str = result;
    return NAME;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 146 "asm6502.l"
{
    // Extract just the data name (without prefix and indexing)
    char* originalText = strdup(yytext);
    char* commaPos = strchr(originalText, ',');
    *commaPos = '\0';  // Terminate string at the comma
    
    // Skip past "a:_data_"
    char* dataName = originalText + 8;
    
    char* result = strdup(dataName);
    free(originalText);
    
    yylval.str = result;
    return NAME;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 162 "asm6502.l"
{
    // Skip past "a:_data_"
    char* dataName = strdup(yytext + 8);
    yylval.str = dataName;
    return NAME;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 169 "asm6502.l"
{
    // Strip the a:_var_ prefix
    char* varRef = strdup(yytext + 7); // Skip past "a:_var_"
    yylval.str = varRef;
    return NAME;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 176 "asm6502.l"
{
    // Strip the _var_ prefix
    char* varName = strdup(yytext + 5); // Skip past "_var_"
    yylval.str = varName;
    return NAME;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 183 "asm6502.l"
{
    // Strip the _label_ prefix and the trailing colon
    char* originalText = strdup(yytext);
    int len = strlen(originalText);
    originalText[len-1] = '\0';  // Remove colon
    char* labelName = originalText + 7;  // Skip past "_label_"
    yylval.str = strdup(labelName);
    free(originalText);  // Free the temporary string
    return LABEL;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 194 "asm6502.l"
{
    // Strip the _label_ prefix for label references (no colon)
    char* labelRef = strdup(yytext + 7); // Skip past "_label_"
    yylval.str = labelRef;
    return NAME;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 201 "asm6502.l"
{
    // Strip the _func_ prefix for function references
    char* funcRef = strdup(yytext + 6); // Skip past "_func_"
    yylval.str = funcRef;
    return NAME;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 208 "asm6502.l"
{
    // Strip the _func_ prefix and the trailing colon
    char* originalText = strdup(yytext);
    int len = strlen(originalText);
    originalText[len-1] = '\0';  // Remove colon
    char* funcName = originalText + 6;  // Skip past "_func_"
    yylval.str = strdup(funcName);
    free(originalText);  // Free the temporary string
    return LABEL;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 219 "asm6502.l"
{
    // Strip the _jump_ prefix
    char* jumpRef = strdup(yytext + 6); // Skip past "_jump_"
    yylval.str = jumpRef;
    return NAME;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 226 "asm6502.l"
{
    yylval.str = DUP_YYTEXT;
    return LABEL;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 231 "asm6502.l"
{
    return 'x'; // Always return lowercase for consistency
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 235 "asm6502.l"
{
    return 'y'; // Always return lowercase for consistency
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 239 "asm6502.l"
{
    return LDA;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 243 "asm6502.l"
{
    return LDX;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 247 "asm6502.l"
{
    return LDY;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 251 "asm6502.l"
{
    return SRE;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 255 "asm6502.l"
{
    return LAX;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 260 "asm6502.l"
{
    return STA;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 264 "asm6502.l"
{
    return STX;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 268 "asm6502.l"
{
    return STY;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 272 "asm6502.l"
{
    return TAX;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 276 "asm6502.l"
{
    return TAY;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 280 "asm6502.l"
{
    return RLA;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 284 "asm6502.l"
{
    return TXA;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 288 "asm6502.l"
{
    return TYA;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 292 "asm6502.l"
{
    return TSX;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 296 "asm6502.l"
{
    return TXS;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 300 "asm6502.l"
{
    return PHA;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 304 "asm6502.l"
{
    return PHP;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 308 "asm6502.l"
{
    return PLA;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 312 "asm6502.l"
{
    return PLP;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 316 "asm6502.l"
{
    return AND;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 320 "asm6502.l"
{
    return EOR;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 324 "asm6502.l"
{
    return ORA;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 328 "asm6502.l"
{
    return BIT;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 331 "asm6502.l"
{
    return DCP;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 334 "asm6502.l"
{
    return ADC;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 338 "asm6502.l"
{
    return SBC;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 342 "asm6502.l"
{
    return CMP;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 346 "asm6502.l"
{
    return CPX;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 350 "asm6502.l"
{
    return CPY;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 354 "asm6502.l"
{
    return INC;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 358 "asm6502.l"
{
    return INX;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 362 "asm6502.l"
{
    return INY;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 366 "asm6502.l"
{
    return DEC;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 370 "asm6502.l"
{
    return SLO;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 374 "asm6502.l"
{
    return DEX;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 378 "asm6502.l"
{
    return DEY;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 382 "asm6502.l"
{
    return ASL;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 386 "asm6502.l"
{
    return LSR;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 390 "asm6502.l"
{
    return ROL;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 394 "asm6502.l"
{
    return ROR;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 398 "asm6502.l"
{
    return JMP;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 402 "asm6502.l"
{
    return JSR;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 406 "asm6502.l"
{
    return RTS;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 410 "asm6502.l"
{
    return BCC;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 414 "asm6502.l"
{
    return BCS;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 418 "asm6502.l"
{
    return BEQ;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 422 "asm6502.l"
{
    return BMI;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 426 "asm6502.l"
{
    return BNE;
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 430 "asm6502.l"
{
    return BPL;
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 434 "asm6502.l"
{
    return BVC;
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 438 "asm6502.l"
{
    return BVS;
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 442 "asm6502.l"
{
    return CLC;
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 446 "asm6502.l"
{
    return CLD;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 450 "asm6502.l"
{
    return CLI;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 454 "asm6502.l"
{
    return CLV;
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 458 "asm6502.l"
{
    return SEC;
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 462 "asm6502.l"
{
    return SED;
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 466 "asm6502.l"
{
    return SEI;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 470 "asm6502.l"
{
    return BRK;
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 474 "asm6502.l"
{
    return NOP;
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 478 "asm6502.l"
{
    return RTI;
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 482 "asm6502.l"
{
    // Custom instruction, handle it like STA
    return STA;
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 487 "asm6502.l"
{
    yylval.str = DUP_YYTEXT;
    return NAME;
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 492 "asm6502.l"
{
    yylval.str = DUP_YYTEXT;
    return HEXCONST;
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 497 "asm6502.l"
{
    yylval.str = DUP_YYTEXT;
    return BINCONST;
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 502 "asm6502.l"
{
    yylval.str = DUP_YYTEXT;
    return DECCONST;
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 507 "asm6502.l"
{
    return *yytext;
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 511 "asm6502.l"
{
    return *yytext;
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 515 "asm6502.l"
{
    return *yytext;
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 519 "asm6502.l"
{
    return *yytext;
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 523 "asm6502.l"
{
    return *yytext;
}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 527 "asm6502.l"
{
    return *yytext;
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 531 "asm6502.l"
{
    return *yytext;
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 535 "asm6502.l"
{
    return *yytext;
}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 539 "asm6502.l"
{
    return *yytext;
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 543 "asm6502.l"
{
    printf("invalid token (line %d): %s\n", yylineno, yytext);
    yyerror(yytext);
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 548 "asm6502.l"
ECHO;
	YY_BREAK
#line 1873 "/home/jbhall/software_build/codegen_6502/test/lexer.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 236 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 236 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 235);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 548 "asm6502.l"


